### ISSUE TITLE
ghurlbot creates a duplicate action when RRSAgent leaves

### ISSUE THREAD

**Issue by pchampin** [w3c/GHURLBot#1]
When RRSAgent leaves, it gives a summary of the recorded actions (e.g. [1]), which triggers ghurlbot to create a duplicate of the action (assuming, of course, that ghurlbot was present when the action was first recorded by RRSAgent).

I think the easiest fix would be for ghurlbot to ignore the actions reported by RRSAgent. A more fancy fix would be a configurable ignorelist.

[1] https://www.w3.org/2022/12/15-rdf-star-irc#T17-59-30

**Comment by bert-github** [comment]
I added an ignore list of IRC nicks that cannot make issues & actions. You can add nicks to it with a command such as

    ghurlbot, ignore rrsagent

The ignore list is per channel. You'll need to repeat the command on all channels where you want the same nick to be ignored. Also, the list is initially empty, i.e., RRSAgent is not automatically added to it.

To remove a nick from the list, replace ‘ignore’ by ‘don't ignore’.

I believe that fixes the issue. But please reopen it if it doesn't work correctly.

Thanks for testing the bot!
