### ISSUE TITLE
support closing issue with full URL

### ISSUE THREAD

**Issue by pchampin** [w3c/GHURLBot#10]
While gb supports closing issue given as hash+number (e.g. `#42`) or repo+hash+number (e.g. `w3c/foo#42`), it does not support closing the same issue if its full URL is given (e.g. `https://github.com/w3c/foo/issues/42`). This is a bit counter-intuitive.

**Comment by bert-github** [comment]
This should now work. You can close, reopen or comment on an issue by giving the full URL of the issue.
