### ISSUE TITLE
order of the repos changes without apparent reason

### ISSUE THREAD

**Issue by pchampin** [w3c/GHURLBot#11]
We are using the `gb` bot with the RDF-star WG, and every now and then, when we start a meeting, the order of the repos has changed without any apparent reason.

It seems to me that he new (undesired) order is the alphabetical order, which might be a hint to the cause of the bug.

**Comment by bert-github** [comment]
Indeed, the bot saved its internal state between sessions in alphabetical order, in an attempt to make debugging easier…

Should now be fixed.
