### ISSUE TITLE
gb should ignore 'subst' and 'insert' commands w

### ISSUE THREAD

**Issue by pchampin** [w3c/GHURLBot#12]
When cleaning up minutes from IRC at the end of a meeting, using `s/x/y` or `i/x/y`,
I sometimes put text in `x` or `y` which triggers a gh reaction, which makes no sense
– especially when the reaction is triggered by the text to remove wit the substitution!

I suggest that gh simply ignores any line starting with `s/`, `s|`, `i/` or `i|`.
Those lines are clearly aimed at another bot, not really part of the conversation.

**Comment by bert-github** [comment]
The bot now ignores s/// and i/// lines.
