### ISSUE TITLE
due date in the next year should be detected

### ISSUE THREAD

**Issue by pchampin** [w3c/GHURLBot#2]
today, when specified "due 2 Jan" for an action, gurlbot set its due date to 2 Jan 2022 ... :wink:

**Comment by bert-github** [comment]
It is tricky to find the correct date in the future. The Date::Manip::Date library I'm using to parse dates does not offer that feature. For now I just added a check if a date is in the past, in which case the bot prints an error and does not create the action.

**Comment by bert-github** [comment]
The bot now adjusts the year when a due date is in the past, and prints a warning when it does so.
