### ISSUE TITLE
feature: comment on existing issue

### ISSUE THREAD

**Issue by coolharsh55** [w3c/GHURLBot#4]
Hi. Would it be possible to add a feature whereby ghurlbot adds comments to an existing issue? Currently, I can only find capability and guidance for creating new issues. Having the ability to quickly add comments to issues would be helpful to ensure issues are updated as per the decisions taken during meetings. Otherwise I have to manually add comments after the meetings.

Syntax e.g. `NOTE <#ISSUE> <text of comment>`. Ideally, the comment generated includes the context e.g. (added during <MEETING>).

The REST call for adding comments is quite similar to existing code regarding creating new issues or closing issues, see docs at https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment

(thanks for the bot - finding it quite helpful to look issues in meetings)

**Comment by bert-github** [comment]
I'm doing some experiments. I'm currently testing two syntaxes:

    Note #37: This is my comment
    Comment #37: This is my comment

where the colon (:) is optional. Still wondering if this syntax could clash with something else, e.g., in RRSAgent.

About adding information about the context: The 'bot can add who made the comment on what channel (and GitHub will add the date and time), but it doesn't know if the comment was made during a meeting, let alone whose meeting. It would need to watch for Zakim…

My experimental version currently adds a line like this before the comment:

    Comment by @foo via IRC channel #bar on irc.w3.org:

**Comment by bert-github** [comment]
I added the commands ‘note’ and ‘comment’ as above and restarted the bot.

**Comment by coolharsh55** [comment]
Used it today, and works as expected. Thanks Bert : )
