### ISSUE TITLE
Reduce or make an alias for 'ghurlbot'

### ISSUE THREAD

**Issue by r12a** [w3c/GHURLBot#6]
Especially while reviewing things like action items during a call, `ghurlbot,` is quite a long thing to type many times in quick succession, and personally i find that my fingers keep tripping over themselves when typing that sequence of characters.

Can we provide an alias such as 'gb'?

**Comment by bert-github** [comment]
The bot now tries by default to use ‘gb’ as its IRC nick. I restarted the instance on irc.w3.org and it now has the new nick.
