### ISSUE TITLE
Allow multiple assignees for a new action

### ISSUE THREAD

**Issue by r12a** [w3c/GHURLBot#7]
It would be nice if it were possible to assign more than one person at a time to an action when it is being created in IRC, rather than having to do that in GitHub later.

Could we perhaps have a syntax such as the following?
````
action tom+dick+harry: do something useful
````

**Comment by r12a** [comment]
It seems that this is already possible using:
````
action tom,dick,harry: do something useful
````

See https://github.com/w3c/GHURLBot/blob/c5afb418243e7006fbe9dd630ce5556d050caa36/ghurlbot.pl#L480 (from Dom)

Perhaps we could add that to the _Creating an action_ section in the documentation.

**Comment by bert-github** [comment]
It is now documented and has an example in the section [‘Creating an action’](https://w3c.github.io/GHURLBot/manual.html#create-action) as well as in the built-in help.

**Comment by r12a** [comment]
Thanks!
