### ISSUE TITLE
Need a way to ignore `@handle` when we know that it doesn't refer to a GitHub user

### ISSUE THREAD

**Issue by TallTed** [w3c/GHURLBot#8]
For instance, when talking about a JSON `@container` or `@set`, we don't want a link to [`https://github.com/container`](https://github.com/container) or [`https://github.com/set`](https://github.com/set).

GitHub Markdown lets us treat those as code, as above ``` `@container` ``` or ``` `@set` ```, so that those GitHub users are not alerted nor otherwise dragged into a conversation against their will, though Markdown isn't generally used in IRC...

We also need a way to remove `gb`'s output lines, such as --
```
https://github.com/container -> @container
```
-- from IRC logs, such that they are not processed into RRSAgent's minutes output. Currently, the RRSAgent line fixer --
```
s|https://github.com/container -> @container||
```
-- does delete the original appearance of that line, but it immediately results in a *new* appearance, as `gb` sees the new occurrence of `@container`.

**Comment by bert-github** [comment]
If you do the s||| command quickly enough, within 15 lines, gb will not expand the new occurrence. But better is probably to turn off recognition of @+name completely, with

    gb, names off

or a similar command (see https://w3c.github.io/GHURLBot/manual.html#suspend). This setting remains associated with the channel, so you only have to do it once.

There is currently no way to protect certain @-words and not others. I'll think about it...

**Comment by pchampin** [comment]
I think there are two parts in this issue:

* preventing the problem, by  using backticks:
  would it be possible for `gb` to simply ignore any `@handle` that is enclosed in backticks, like github-markdown does?
* being able to fix the problem with `s//`:
  I believe this is covered by #12

**Comment by bert-github** [comment]
The bot should now ignore text in backquotes and it also ignores lines that look like substitutions and insertions (see #12).

Like in MarkDown, the number of backquotes before and after must match: ` ```...``` ` is skipped, but ` ```...`` ` is not.
