### ISSUE TITLE
support "gb, close <issue>"

### ISSUE THREAD

**Issue by pchampin** [w3c/GHURLBot#9]
currently, most commands are invoked as `gb, command`,  but closing an issue is performed with `close <issue>`. `gb, close <issue>`, on the other hand, seems to be not recognized by GHURLBot.

For the sake of regularity, it would be better if GHURLBot supported `gb, close <issue>`.

**Comment by bert-github** [comment]
It is supposed to work...

Can you show me exactly what you tried?

**Comment by pchampin** [comment]
apologies, when we tried it, it didn't work.
We must have done something wrong, but since "gb, close #N" was not explicitly documented, I hastily concluded that the problem was with gb rather than us... :-)

**Comment by pchampin** [comment]
I finally found what we did wrong. Submitted #10 about :)
